services:
  node:
    # Используем образ из Harbor вместо локальной сборки
    image: registry.konstpic.ru/3x-ui/node:latest
    container_name: 3x-ui-node
    restart: unless-stopped
    #environment:
      #- NODE_API_KEY=test-key
      #- PANEL_URL=http://192.168.0.7:2054
    ports:
      - "8080:8080"  # API ports (connect panel)
     # - "44000:44000" # Xray ports = Inbound port
     # - "8443:8443"  # HTTPS API port (uncomment if using HTTPS)
    volumes:
      - ./bin:/app/bin
      - ./logs:/app/logs
      - ./cert:/app/cert  # Mount directory for TLS certificates
      - ./data:/app/data  # Data folder for core state and geo files
      # Note: bin directory is mounted for persistence
      # If config.json doesn't exist, it will be created when XRAY config is first applied
      # If ./bin/config.json on host is a directory, XRAY will use an alternative path automatically
      # Place your TLS certificates in ./cert/ directory:
      #   - cert.pem (or fullchain.pem)
      #   - key.pem (or privkey.pem)
    environment:
      # Uncomment and set paths to enable HTTPS:
      # - NODE_TLS_CERT_FILE=/app/cert/cert.pem
      # - NODE_TLS_KEY_FILE=/app/cert/key.pem
    networks:
      - xray-network
networks:
  xray-network:
    driver: bridge
